// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sandbox.proto

// Package aries.sandbox.v1 is the wire contract between an agent harness and
// the ARIES tool bridge. The bridge serves it from the ARIES process on the
// task network gateway; the task container itself serves nothing and runs no
// daemon. See docs/design/grpc-bridge.md.

package sandboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sandbox_Exec_FullMethodName      = "/aries.sandbox.v1.Sandbox/Exec"
	Sandbox_Stat_FullMethodName      = "/aries.sandbox.v1.Sandbox/Stat"
	Sandbox_ReadFile_FullMethodName  = "/aries.sandbox.v1.Sandbox/ReadFile"
	Sandbox_ReadLines_FullMethodName = "/aries.sandbox.v1.Sandbox/ReadLines"
	Sandbox_WriteFile_FullMethodName = "/aries.sandbox.v1.Sandbox/WriteFile"
)

// SandboxClient is the client API for Sandbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sandbox grants a harness narrow, audited, revocable access to one task
// sandbox. Exec runs a script; the four file procedures move bytes without a
// shell. Paths are absolute inside the sandbox; the caller resolves relative
// paths before the call. Every procedure is refused with UNAVAILABLE once the
// session is revoked, and with UNIMPLEMENTED when the sandbox offers no file
// access.
type SandboxClient interface {
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Stat reports what is at a path without reading it. Absence is a normal
	// answer (exists=false), not an error, so callers can probe cheaply.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// ReadFile streams a byte range of a regular file: a header, then chunks.
	// It serves whole-file reads and the small probes (binary sample, BOM, line
	// ending). File content has no size bound.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileResponse], error)
	// ReadLines streams a window of lines, then the counts a paginated text read
	// needs, computed next to the data so only the window crosses the wire. It
	// matches `sed -n 'a,bp' | cut -b1-N`, `wc -l`, and a trailing-newline
	// check, in one pass.
	ReadLines(ctx context.Context, in *ReadLinesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadLinesResponse], error)
	// WriteFile replaces or creates a regular file with exactly the streamed
	// bytes: a header, then chunks, then the client half-closes. A reader sees
	// the old file or the new one, never a prefix; missing parent directories
	// are created. The file changes only if exactly header.size bytes arrived.
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error)
}

type sandboxClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxClient(cc grpc.ClientConnInterface) SandboxClient {
	return &sandboxClient{cc}
}

func (c *sandboxClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, Sandbox_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, Sandbox_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[0], Sandbox_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, ReadFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ReadFileClient = grpc.ServerStreamingClient[ReadFileResponse]

func (c *sandboxClient) ReadLines(ctx context.Context, in *ReadLinesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadLinesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[1], Sandbox_ReadLines_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadLinesRequest, ReadLinesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ReadLinesClient = grpc.ServerStreamingClient[ReadLinesResponse]

func (c *sandboxClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[2], Sandbox_WriteFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileRequest, WriteFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_WriteFileClient = grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse]

// SandboxServer is the server API for Sandbox service.
// All implementations must embed UnimplementedSandboxServer
// for forward compatibility.
//
// Sandbox grants a harness narrow, audited, revocable access to one task
// sandbox. Exec runs a script; the four file procedures move bytes without a
// shell. Paths are absolute inside the sandbox; the caller resolves relative
// paths before the call. Every procedure is refused with UNAVAILABLE once the
// session is revoked, and with UNIMPLEMENTED when the sandbox offers no file
// access.
type SandboxServer interface {
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Stat reports what is at a path without reading it. Absence is a normal
	// answer (exists=false), not an error, so callers can probe cheaply.
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// ReadFile streams a byte range of a regular file: a header, then chunks.
	// It serves whole-file reads and the small probes (binary sample, BOM, line
	// ending). File content has no size bound.
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileResponse]) error
	// ReadLines streams a window of lines, then the counts a paginated text read
	// needs, computed next to the data so only the window crosses the wire. It
	// matches `sed -n 'a,bp' | cut -b1-N`, `wc -l`, and a trailing-newline
	// check, in one pass.
	ReadLines(*ReadLinesRequest, grpc.ServerStreamingServer[ReadLinesResponse]) error
	// WriteFile replaces or creates a regular file with exactly the streamed
	// bytes: a header, then chunks, then the client half-closes. A reader sees
	// the old file or the new one, never a prefix; missing parent directories
	// are created. The file changes only if exactly header.size bytes arrived.
	WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error
	mustEmbedUnimplementedSandboxServer()
}

// UnimplementedSandboxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServer struct{}

func (UnimplementedSandboxServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSandboxServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxServer) ReadLines(*ReadLinesRequest, grpc.ServerStreamingServer[ReadLinesResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadLines not implemented")
}
func (UnimplementedSandboxServer) WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxServer) mustEmbedUnimplementedSandboxServer() {}
func (UnimplementedSandboxServer) testEmbeddedByValue()                 {}

// UnsafeSandboxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServer will
// result in compilation errors.
type UnsafeSandboxServer interface {
	mustEmbedUnimplementedSandboxServer()
}

func RegisterSandboxServer(s grpc.ServiceRegistrar, srv SandboxServer) {
	// If the following call panics, it indicates UnimplementedSandboxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sandbox_ServiceDesc, srv)
}

func _Sandbox_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, ReadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ReadFileServer = grpc.ServerStreamingServer[ReadFileResponse]

func _Sandbox_ReadLines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadLinesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServer).ReadLines(m, &grpc.GenericServerStream[ReadLinesRequest, ReadLinesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ReadLinesServer = grpc.ServerStreamingServer[ReadLinesResponse]

func _Sandbox_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServer).WriteFile(&grpc.GenericServerStream[WriteFileRequest, WriteFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_WriteFileServer = grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]

// Sandbox_ServiceDesc is the grpc.ServiceDesc for Sandbox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sandbox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aries.sandbox.v1.Sandbox",
	HandlerType: (*SandboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _Sandbox_Exec_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Sandbox_Stat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _Sandbox_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadLines",
			Handler:       _Sandbox_ReadLines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _Sandbox_WriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sandbox.proto",
}
