// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sandbox.proto

// Package aries.sandbox.v1 is the wire contract between an agent harness and
// the ARIES tool bridge. The bridge serves it from the ARIES process on the
// task network gateway; the task container itself serves nothing and runs no
// daemon. See docs/design/grpc-bridge.md.

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reason distinguishes how a command ended, so a caller can tell a command that
// failed from a bridge that did. The SSH transport has to flatten all of these
// into exit code 255.
type Reason int32

const (
	Reason_REASON_UNSPECIFIED           Reason = 0
	Reason_REASON_COMPLETED             Reason = 1
	Reason_REASON_CANCELED              Reason = 2
	Reason_REASON_TIMED_OUT             Reason = 3
	Reason_REASON_OUTPUT_LIMIT_EXCEEDED Reason = 4
	Reason_REASON_SANDBOX_ERROR         Reason = 5
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_COMPLETED",
		2: "REASON_CANCELED",
		3: "REASON_TIMED_OUT",
		4: "REASON_OUTPUT_LIMIT_EXCEEDED",
		5: "REASON_SANDBOX_ERROR",
	}
	Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":           0,
		"REASON_COMPLETED":             1,
		"REASON_CANCELED":              2,
		"REASON_TIMED_OUT":             3,
		"REASON_OUTPUT_LIMIT_EXCEEDED": 4,
		"REASON_SANDBOX_ERROR":         5,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[0].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[0]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

// ExecRequest carries only what crosses the wire today. The bridge sets the
// working directory itself and passes no environment, so neither is a field
// here; docs/design/grpc-bridge.md records why each omission is deliberate and
// what would bring it back.
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// script runs under /bin/bash -c in the sandbox, uninterpreted by the bridge.
	Script string `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	// stdin is bounded. Large input belongs in WriteFile, which streams.
	Stdin         []byte `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

// ExecResponse is returned with an OK status even when the command failed. A
// non-zero exit_code is a task outcome, not an RPC error; RPC error statuses
// are reserved for bridge-level failures.
type ExecResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ExitCode int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason   Reason                 `protobuf:"varint,2,opt,name=reason,proto3,enum=aries.sandbox.v1.Reason" json:"reason,omitempty"`
	// stdout and stderr stay separate rather than interleaved, which is stricter
	// than SSH's extended-data channel.
	Stdout []byte `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr []byte `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// truncated reports that output reached the bridge's cap and was cut.
	Truncated     bool `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetReason() Reason {
	if x != nil {
		return x.Reason
	}
	return Reason_REASON_UNSPECIFIED
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\x10aries.sandbox.v1\";\n" +
	"\vExecRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\"\xab\x01\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x120\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x18.aries.sandbox.v1.ReasonR\x06reason\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\fR\x06stderr\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated*\x9d\x01\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REASON_COMPLETED\x10\x01\x12\x13\n" +
	"\x0fREASON_CANCELED\x10\x02\x12\x14\n" +
	"\x10REASON_TIMED_OUT\x10\x03\x12 \n" +
	"\x1cREASON_OUTPUT_LIMIT_EXCEEDED\x10\x04\x12\x18\n" +
	"\x14REASON_SANDBOX_ERROR\x10\x052P\n" +
	"\aSandbox\x12E\n" +
	"\x04Exec\x12\x1d.aries.sandbox.v1.ExecRequest\x1a\x1e.aries.sandbox.v1.ExecResponseB>Z<github.com/hyscale-lab/aries/pkg/bridge/hermesgrpc/sandboxv1b\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandbox_proto_goTypes = []any{
	(Reason)(0),          // 0: aries.sandbox.v1.Reason
	(*ExecRequest)(nil),  // 1: aries.sandbox.v1.ExecRequest
	(*ExecResponse)(nil), // 2: aries.sandbox.v1.ExecResponse
}
var file_sandbox_proto_depIdxs = []int32{
	0, // 0: aries.sandbox.v1.ExecResponse.reason:type_name -> aries.sandbox.v1.Reason
	1, // 1: aries.sandbox.v1.Sandbox.Exec:input_type -> aries.sandbox.v1.ExecRequest
	2, // 2: aries.sandbox.v1.Sandbox.Exec:output_type -> aries.sandbox.v1.ExecResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
