// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/bridge/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BridgeControl_AssignSandbox_FullMethodName    = "/aries.bridge.control.v1.BridgeControl/AssignSandbox"
	BridgeControl_GetAssignment_FullMethodName    = "/aries.bridge.control.v1.BridgeControl/GetAssignment"
	BridgeControl_RevokeAssignment_FullMethodName = "/aries.bridge.control.v1.BridgeControl/RevokeAssignment"
)

// BridgeControlClient is the client API for BridgeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeControlClient interface {
	AssignSandbox(ctx context.Context, in *AssignSandboxRequest, opts ...grpc.CallOption) (*Assignment, error)
	GetAssignment(ctx context.Context, in *AssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
	RevokeAssignment(ctx context.Context, in *AssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
}

type bridgeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeControlClient(cc grpc.ClientConnInterface) BridgeControlClient {
	return &bridgeControlClient{cc}
}

func (c *bridgeControlClient) AssignSandbox(ctx context.Context, in *AssignSandboxRequest, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, BridgeControl_AssignSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeControlClient) GetAssignment(ctx context.Context, in *AssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, BridgeControl_GetAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeControlClient) RevokeAssignment(ctx context.Context, in *AssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, BridgeControl_RevokeAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeControlServer is the server API for BridgeControl service.
// All implementations must embed UnimplementedBridgeControlServer
// for forward compatibility.
type BridgeControlServer interface {
	AssignSandbox(context.Context, *AssignSandboxRequest) (*Assignment, error)
	GetAssignment(context.Context, *AssignmentRequest) (*Assignment, error)
	RevokeAssignment(context.Context, *AssignmentRequest) (*Assignment, error)
	mustEmbedUnimplementedBridgeControlServer()
}

// UnimplementedBridgeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeControlServer struct{}

func (UnimplementedBridgeControlServer) AssignSandbox(context.Context, *AssignSandboxRequest) (*Assignment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignSandbox not implemented")
}
func (UnimplementedBridgeControlServer) GetAssignment(context.Context, *AssignmentRequest) (*Assignment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignment not implemented")
}
func (UnimplementedBridgeControlServer) RevokeAssignment(context.Context, *AssignmentRequest) (*Assignment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAssignment not implemented")
}
func (UnimplementedBridgeControlServer) mustEmbedUnimplementedBridgeControlServer() {}
func (UnimplementedBridgeControlServer) testEmbeddedByValue()                       {}

// UnsafeBridgeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeControlServer will
// result in compilation errors.
type UnsafeBridgeControlServer interface {
	mustEmbedUnimplementedBridgeControlServer()
}

func RegisterBridgeControlServer(s grpc.ServiceRegistrar, srv BridgeControlServer) {
	// If the following call pancis, it indicates UnimplementedBridgeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BridgeControl_ServiceDesc, srv)
}

func _BridgeControl_AssignSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeControlServer).AssignSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeControl_AssignSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeControlServer).AssignSandbox(ctx, req.(*AssignSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeControl_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeControlServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeControl_GetAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeControlServer).GetAssignment(ctx, req.(*AssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeControl_RevokeAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeControlServer).RevokeAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeControl_RevokeAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeControlServer).RevokeAssignment(ctx, req.(*AssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeControl_ServiceDesc is the grpc.ServiceDesc for BridgeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aries.bridge.control.v1.BridgeControl",
	HandlerType: (*BridgeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignSandbox",
			Handler:    _BridgeControl_AssignSandbox_Handler,
		},
		{
			MethodName: "GetAssignment",
			Handler:    _BridgeControl_GetAssignment_Handler,
		},
		{
			MethodName: "RevokeAssignment",
			Handler:    _BridgeControl_RevokeAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/control/v1/control.proto",
}
