// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/bridge/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_REGISTERING       State = 1
	State_READY             State = 2
	State_RELEASING         State = 3
	State_RELEASED          State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "REGISTERING",
		2: "READY",
		3: "RELEASING",
		4: "RELEASED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"REGISTERING":       1,
		"READY":             2,
		"RELEASING":         3,
		"RELEASED":          4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_bridge_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_pkg_bridge_control_v1_control_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,6,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Workdir       string                 `protobuf:"bytes,12,opt,name=workdir,proto3" json:"workdir,omitempty"`
	ExecUser      string                 `protobuf:"bytes,13,opt,name=exec_user,json=execUser,proto3" json:"exec_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *Target) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Target) GetExecUser() string {
	if x != nil {
		return x.ExecUser
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RegisterSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSandboxRequest) Reset() {
	*x = RegisterSandboxRequest{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSandboxRequest) ProtoMessage() {}

func (x *RegisterSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSandboxRequest.ProtoReflect.Descriptor instead.
func (*RegisterSandboxRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RegisterSandboxRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RegisterSandboxRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxRequest) Reset() {
	*x = SandboxRequest{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxRequest) ProtoMessage() {}

func (x *SandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxRequest.ProtoReflect.Descriptor instead.
func (*SandboxRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Transport     string                 `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Endpoint) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type SandboxAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=aries.bridge.control.v1.State" json:"state,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CleanupError  string                 `protobuf:"bytes,6,opt,name=cleanup_error,json=cleanupError,proto3" json:"cleanup_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxAccess) Reset() {
	*x = SandboxAccess{}
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxAccess) ProtoMessage() {}

func (x *SandboxAccess) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxAccess.ProtoReflect.Descriptor instead.
func (*SandboxAccess) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxAccess) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxAccess) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *SandboxAccess) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *SandboxAccess) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *SandboxAccess) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SandboxAccess) GetCleanupError() string {
	if x != nil {
		return x.CleanupError
	}
	return ""
}

var File_pkg_bridge_control_v1_control_proto protoreflect.FileDescriptor

const file_pkg_bridge_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"#pkg/bridge/control/v1/control.proto\x12\x17aries.bridge.control.v1\"\xea\x01\n" +
	"\x06Target\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x06 \x01(\tR\truntimeId\x12\x18\n" +
	"\aworkdir\x18\f \x01(\tR\aworkdir\x12\x1b\n" +
	"\texec_user\x18\r \x01(\tR\bexecUserJ\x04\b\x01\x10\x06J\x04\b\a\x10\fJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10R\aversionR\x06run_idR\atask_idR\roccurrence_idR\abackendR\fruntime_nameR\x0fexpected_labelsR\x0fmax_input_bytesR\x10max_output_bytes\"#\n" +
	"\bMetadata\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xaf\x01\n" +
	"\x16RegisterSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x127\n" +
	"\x06target\x18\x02 \x01(\v2\x1f.aries.bridge.control.v1.TargetR\x06target\x12=\n" +
	"\bmetadata\x18\x03 \x01(\v2!.aries.bridge.control.v1.MetadataR\bmetadata\"/\n" +
	"\x0eSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"l\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\tR\ttransportJ\x04\b\x01\x10\x02J\x04\b\x05\x10\x06R\x04hostR\bhost_key\"b\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\x9f\x02\n" +
	"\rSandboxAccess\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.aries.bridge.control.v1.StateR\x05state\x12=\n" +
	"\bendpoint\x18\x03 \x01(\v2!.aries.bridge.control.v1.EndpointR\bendpoint\x12?\n" +
	"\tartifacts\x18\x04 \x03(\v2!.aries.bridge.control.v1.ArtifactR\tartifacts\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12#\n" +
	"\rcleanup_error\x18\x06 \x01(\tR\fcleanupError*W\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vREGISTERING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\r\n" +
	"\tRELEASING\x10\x03\x12\f\n" +
	"\bRELEASED\x10\x042\xbd\x02\n" +
	"\rBridgeControl\x12j\n" +
	"\x0fRegisterSandbox\x12/.aries.bridge.control.v1.RegisterSandboxRequest\x1a&.aries.bridge.control.v1.SandboxAccess\x12]\n" +
	"\n" +
	"GetSandbox\x12'.aries.bridge.control.v1.SandboxRequest\x1a&.aries.bridge.control.v1.SandboxAccess\x12a\n" +
	"\x0eReleaseSandbox\x12'.aries.bridge.control.v1.SandboxRequest\x1a&.aries.bridge.control.v1.SandboxAccessB>Z<github.com/hyscale-lab/aries/pkg/bridge/control/v1;controlv1b\x06proto3"

var (
	file_pkg_bridge_control_v1_control_proto_rawDescOnce sync.Once
	file_pkg_bridge_control_v1_control_proto_rawDescData []byte
)

func file_pkg_bridge_control_v1_control_proto_rawDescGZIP() []byte {
	file_pkg_bridge_control_v1_control_proto_rawDescOnce.Do(func() {
		file_pkg_bridge_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_bridge_control_v1_control_proto_rawDesc), len(file_pkg_bridge_control_v1_control_proto_rawDesc)))
	})
	return file_pkg_bridge_control_v1_control_proto_rawDescData
}

var file_pkg_bridge_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_bridge_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_bridge_control_v1_control_proto_goTypes = []any{
	(State)(0),                     // 0: aries.bridge.control.v1.State
	(*Target)(nil),                 // 1: aries.bridge.control.v1.Target
	(*Metadata)(nil),               // 2: aries.bridge.control.v1.Metadata
	(*RegisterSandboxRequest)(nil), // 3: aries.bridge.control.v1.RegisterSandboxRequest
	(*SandboxRequest)(nil),         // 4: aries.bridge.control.v1.SandboxRequest
	(*Endpoint)(nil),               // 5: aries.bridge.control.v1.Endpoint
	(*Artifact)(nil),               // 6: aries.bridge.control.v1.Artifact
	(*SandboxAccess)(nil),          // 7: aries.bridge.control.v1.SandboxAccess
}
var file_pkg_bridge_control_v1_control_proto_depIdxs = []int32{
	1, // 0: aries.bridge.control.v1.RegisterSandboxRequest.target:type_name -> aries.bridge.control.v1.Target
	2, // 1: aries.bridge.control.v1.RegisterSandboxRequest.metadata:type_name -> aries.bridge.control.v1.Metadata
	0, // 2: aries.bridge.control.v1.SandboxAccess.state:type_name -> aries.bridge.control.v1.State
	5, // 3: aries.bridge.control.v1.SandboxAccess.endpoint:type_name -> aries.bridge.control.v1.Endpoint
	6, // 4: aries.bridge.control.v1.SandboxAccess.artifacts:type_name -> aries.bridge.control.v1.Artifact
	3, // 5: aries.bridge.control.v1.BridgeControl.RegisterSandbox:input_type -> aries.bridge.control.v1.RegisterSandboxRequest
	4, // 6: aries.bridge.control.v1.BridgeControl.GetSandbox:input_type -> aries.bridge.control.v1.SandboxRequest
	4, // 7: aries.bridge.control.v1.BridgeControl.ReleaseSandbox:input_type -> aries.bridge.control.v1.SandboxRequest
	7, // 8: aries.bridge.control.v1.BridgeControl.RegisterSandbox:output_type -> aries.bridge.control.v1.SandboxAccess
	7, // 9: aries.bridge.control.v1.BridgeControl.GetSandbox:output_type -> aries.bridge.control.v1.SandboxAccess
	7, // 10: aries.bridge.control.v1.BridgeControl.ReleaseSandbox:output_type -> aries.bridge.control.v1.SandboxAccess
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_bridge_control_v1_control_proto_init() }
func file_pkg_bridge_control_v1_control_proto_init() {
	if File_pkg_bridge_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_bridge_control_v1_control_proto_rawDesc), len(file_pkg_bridge_control_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_bridge_control_v1_control_proto_goTypes,
		DependencyIndexes: file_pkg_bridge_control_v1_control_proto_depIdxs,
		EnumInfos:         file_pkg_bridge_control_v1_control_proto_enumTypes,
		MessageInfos:      file_pkg_bridge_control_v1_control_proto_msgTypes,
	}.Build()
	File_pkg_bridge_control_v1_control_proto = out.File
	file_pkg_bridge_control_v1_control_proto_goTypes = nil
	file_pkg_bridge_control_v1_control_proto_depIdxs = nil
}
