// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/bridge/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BridgeControl_RegisterSandbox_FullMethodName = "/aries.bridge.control.v1.BridgeControl/RegisterSandbox"
	BridgeControl_GetSandbox_FullMethodName      = "/aries.bridge.control.v1.BridgeControl/GetSandbox"
	BridgeControl_ReleaseSandbox_FullMethodName  = "/aries.bridge.control.v1.BridgeControl/ReleaseSandbox"
)

// BridgeControlClient is the client API for BridgeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeControlClient interface {
	RegisterSandbox(ctx context.Context, in *RegisterSandboxRequest, opts ...grpc.CallOption) (*SandboxAccess, error)
	GetSandbox(ctx context.Context, in *SandboxRequest, opts ...grpc.CallOption) (*SandboxAccess, error)
	ReleaseSandbox(ctx context.Context, in *SandboxRequest, opts ...grpc.CallOption) (*SandboxAccess, error)
}

type bridgeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeControlClient(cc grpc.ClientConnInterface) BridgeControlClient {
	return &bridgeControlClient{cc}
}

func (c *bridgeControlClient) RegisterSandbox(ctx context.Context, in *RegisterSandboxRequest, opts ...grpc.CallOption) (*SandboxAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxAccess)
	err := c.cc.Invoke(ctx, BridgeControl_RegisterSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeControlClient) GetSandbox(ctx context.Context, in *SandboxRequest, opts ...grpc.CallOption) (*SandboxAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxAccess)
	err := c.cc.Invoke(ctx, BridgeControl_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeControlClient) ReleaseSandbox(ctx context.Context, in *SandboxRequest, opts ...grpc.CallOption) (*SandboxAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxAccess)
	err := c.cc.Invoke(ctx, BridgeControl_ReleaseSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeControlServer is the server API for BridgeControl service.
// All implementations must embed UnimplementedBridgeControlServer
// for forward compatibility.
type BridgeControlServer interface {
	RegisterSandbox(context.Context, *RegisterSandboxRequest) (*SandboxAccess, error)
	GetSandbox(context.Context, *SandboxRequest) (*SandboxAccess, error)
	ReleaseSandbox(context.Context, *SandboxRequest) (*SandboxAccess, error)
	mustEmbedUnimplementedBridgeControlServer()
}

// UnimplementedBridgeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeControlServer struct{}

func (UnimplementedBridgeControlServer) RegisterSandbox(context.Context, *RegisterSandboxRequest) (*SandboxAccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSandbox not implemented")
}
func (UnimplementedBridgeControlServer) GetSandbox(context.Context, *SandboxRequest) (*SandboxAccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedBridgeControlServer) ReleaseSandbox(context.Context, *SandboxRequest) (*SandboxAccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSandbox not implemented")
}
func (UnimplementedBridgeControlServer) mustEmbedUnimplementedBridgeControlServer() {}
func (UnimplementedBridgeControlServer) testEmbeddedByValue()                       {}

// UnsafeBridgeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeControlServer will
// result in compilation errors.
type UnsafeBridgeControlServer interface {
	mustEmbedUnimplementedBridgeControlServer()
}

func RegisterBridgeControlServer(s grpc.ServiceRegistrar, srv BridgeControlServer) {
	// If the following call pancis, it indicates UnimplementedBridgeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BridgeControl_ServiceDesc, srv)
}

func _BridgeControl_RegisterSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeControlServer).RegisterSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeControl_RegisterSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeControlServer).RegisterSandbox(ctx, req.(*RegisterSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeControl_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeControlServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeControl_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeControlServer).GetSandbox(ctx, req.(*SandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeControl_ReleaseSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeControlServer).ReleaseSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeControl_ReleaseSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeControlServer).ReleaseSandbox(ctx, req.(*SandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeControl_ServiceDesc is the grpc.ServiceDesc for BridgeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aries.bridge.control.v1.BridgeControl",
	HandlerType: (*BridgeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSandbox",
			Handler:    _BridgeControl_RegisterSandbox_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _BridgeControl_GetSandbox_Handler,
		},
		{
			MethodName: "ReleaseSandbox",
			Handler:    _BridgeControl_ReleaseSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/bridge/control/v1/control.proto",
}
